"""add status to appointments

Revision ID: 07c3bf08d33a
Revises: 350c16944394
Create Date: 2026-04-04 18:27:22.456375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07c3bf08d33a'
down_revision = '350c16944394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('unique_appointment_time'), type_='unique')

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=80),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=255),
               nullable=True)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('unique_appointment_time'), ['when'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
